-- init.sql.tpl

CREATE USER IF NOT EXISTS :DEV_ADMIN_USER WITH PASSWORD ':DEV_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE :POSTGRES_DB TO :DEV_ADMIN_USER;

CREATE USER IF NOT EXISTS :API_ACCESS_USER WITH PASSWORD ':API_ACCESS_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :API_ACCESS_USER;