CREATE ROLE secrets_reader;
CREATE ROLE secrets_writer;

CREATE USER IF NOT EXISTS :SECRETS_READ_USER WITH PASSWORD ':SECRETS_READ_PASSWORD';
GRANT secrets_reader TO :SECRETS_READ_USER;

CREATE USER IF NOT EXISTS :SECRETS_WRITE_USER WITH PASSWORD ':SECRETS_WRITE_PASSWORD';
GRANT secrets_writer TO :SECRETS_WRITE_USER;